# bsi_schema_embed.cmake -- configure-time embedding of the contract (contract artifact).
#  * refuses to configure when contract/check_contract.py is red (the host must
#    never be built against a contract whose pin does not match its bytes)
#  * generates ${OUT} with the schema text and the pinned CONTRACT_SHA256.
# Inputs: BSI_CONTRACT_DIR, BSI_EMBED_OUT
find_package(Python3 COMPONENTS Interpreter REQUIRED)
execute_process(COMMAND ${Python3_EXECUTABLE} "${BSI_CONTRACT_DIR}/check_contract.py"
                RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
if(NOT _rc EQUAL 0)
    if(BSI_HOST_DEV_UNPINNED)
        message(WARNING "contract hash check failed; continuing because BSI_HOST_DEV_UNPINNED=ON (development only, never CI):\n${_out}${_err}")
    else()
        message(FATAL_ERROR "contract hash check failed (refusing to build a host against an unpinned contract; re-pin with check_contract.py --write):\n${_out}${_err}")
    endif()
endif()
file(READ "${BSI_CONTRACT_DIR}/CONTRACT_SHA256" _sha)
string(STRIP "${_sha}" _sha)
file(READ "${BSI_CONTRACT_DIR}/bsi.schema.json" _schema HEX)
string(LENGTH "${_schema}" _hexlen)
math(EXPR _bytes "${_hexlen} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _schema_c "${_schema}")
file(WRITE "${BSI_EMBED_OUT}"
"// generated by bsi_schema_embed.cmake -- do not edit\n"
"#include <cstddef>\n"
"namespace bsi { namespace schema {\n"
"static const unsigned char kSchemaBytes[] = {${_schema_c} 0x00};\n"
"extern const char* const kEmbeddedSchemaText = (const char*)kSchemaBytes;\n"
"extern const unsigned long kEmbeddedSchemaBytes = ${_bytes}UL;\n"
"extern const char* const kEmbeddedContractSha256 = \"${_sha}\";\n"
"}}\n")
message(STATUS "BSI contract ${_sha} embedded (${_bytes} schema bytes)")
